Check all env vars for existence on startup; Add .env-sample (#200)
The node can be tricky to start up, as you discover new env vars each
time one is missing. This PR adds an abstraction over the environment,
and prints out all missing (required) env vars at startup. This PR also
updates the readme to include all currently required env vars, and
provides a `.env.sample`.

This is what the error looks like if there are missing variables:
```
thread 'main' panicked at crates/node/src/environment.rs:40:13:
Environment variables missing: SECRET_KEY, BLOCKS_PROCESSED_PATH, BATCH_INTERVAL, EO_CONTRACT_ADDRESS, ETH_RPC_URL, COMPUTE_RPC_URL, STORAGE_RPC_URL,
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

---------

Co-authored-by: [eureka@nixos] <57543709+eureka-cpu@users.noreply.github.com>
Co-authored-by: eureka-cpu <github.eureka@gmail.com>